/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package slave

import com.fasterxml.jackson.databind.SerializationFeature
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import io.ktor.application.*
import io.ktor.client.features.json.*
import io.ktor.features.*
import io.ktor.jackson.*
import io.ktor.request.*
import io.ktor.routing.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

    embeddedServer(Netty, port = 8666) {
        install(ContentNegotiation) {
            jackson()
        }

        routing {
            post("job") {
                val req = call.receive<JobStartRequest>()
            }
        }
    }
}

data class JobStartRequest(
    val instanceId: String,
)
